config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :snippets
  devise_for :users

  get '/admin_index' => 'snippets#admin_index'

  root 'welcome#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar, styles: { large: "400x400>", thumb: "80x80>" },  default_url: "/images/:style/missing.png",
          :storage => :s3,
           :url => ':s3_domain_url',
           :path => '/:class/:attachment/:id_partition/:style/:filename',
           :s3_host_name => 's3-us-west-2.amazonaws.com'

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  belongs_to :user

  def time_since_written
    time_elapsed = ((Date.today - created_at) / 1).round
      if time_elapsed < 1
        return "today."
      else
        return "#{time_elapsed} days ago."
      end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :snippets
  has_one :profile
  # Include default devise modules. Others available are:
  # Need to activate Omniauthabl to use FB still :omniauthable
  # Also need to reactivate :confirmable to resume email confirmations
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable, :timeoutable#, :confirmable

  def profile_bonus
    profile_bonus = 0
    if self.profile && self.profile.about_me.length > 75
      profile_bonus = 10
    end
    profile_bonus
  end

  def snippet_bonus
    snippet_bonus = 0
    if self.snippets && self.snippets.count > 0
      snippet_bonus = 5
    end
    snippet_bonus
  end

  def points
    #free points
    #users get more points for being earlier to sign up; how it works: all users get a point for every user that signs up after them, so with 10 users, the 1st user gets 10 points, and the last user gets zero. when 11th user signs up, each of those users gets one more point.
    free_points = User.count - self.id
    total_points = free_points + self.profile_bonus + self.snippet_bonus
  end

  def rank
    all_users = User.all
    #sort users by most points to least points
    all_users_sorted = all_users.sort { |a,b| b.points <=> a.points}
    all_users_sorted.index(self) + 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all.sort { |a,b| b.user.points <=> a.user.points}
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    puts "trying to load /profiles/new"
    if current_user.profile
      redirect_to "/profiles/#{current_user.id}"
    else
    @profile = Profile.new
    end
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    if current_user.profile
      #ERROR: kick user back to their profile page & tell them they can only create one profile.
      respond_to do |format|
        format.html { redirect_to "/profiles/#{current_user.id}", notice: 'Cannot create more than one profile. Your profile already exists.' }
      end
    else
      @profile.user_id = current_user.id
      respond_to do |format|
        if @profile.save
          format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
          format.json { render :show, status: :created, location: @profile }
        else
          format.html { render :new }
          format.json { render json: @profile.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :city, :state, :age, :about_me, :display_name, :political_affiliation, :avatar)
    end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :set_snippet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /snippets
  # GET /snippets.json
  def index
    @snippets = Snippet.where(user_id:current_user.id)
  end

  def admin_index
    if current_user.email == "bbensch@gmail.com"
      @snippets = Snippet.all
      render 'index'
    else
      @snippets = Snippet.where(user_id:current_user.id)
      render 'index'
    end
  end

  # GET /snippets/1
  # GET /snippets/1.json
  def show
  end

  # GET /snippets/new
  def new
    @snippet = Snippet.new
  end

  # GET /snippets/1/edit
  def edit
  end

  # POST /snippets
  # POST /snippets.json
  def create
    @snippet = Snippet.new(snippet_params)
    @snippet.user_id = current_user.id
    @user = current_user

    respond_to do |format|
      if @snippet.save
        puts "Ready to send snippet confirmation email."
        UserMailer.thank_you_for_snippet(@snippet,@user).deliver_now
        format.html { redirect_to @snippet, notice: 'Snippet was successfully created.' }
        format.json { render :show, status: :created, location: @snippet }
      else
        format.html { render :new }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snippets/1
  # PATCH/PUT /snippets/1.json
  def update
    respond_to do |format|
      if @snippet.update(snippet_params)
        format.html { redirect_to @snippet, notice: 'Snippet was successfully updated.' }
        format.json { render :show, status: :ok, location: @snippet }
      else
        format.html { render :edit }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    @snippet.destroy
    respond_to do |format|
      format.html { redirect_to snippets_url, notice: 'Snippet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snippet
      @snippet = Snippet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snippet_params
      params.require(:snippet).permit(:body, :rating, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PAGE TITLE</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,700,300' rel='stylesheet' type='text/css'>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"  crossorigin="anonymous"></script>
  <script type="text/javascript" src="/javascripts/home_scroller.js"></script>
  <!-- <link rel="stylesheet" href="/stylesheets/swiper.min.css">
  <link rel="stylesheet" href="/stylesheets/swiper_config.css"> -->
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default sticky-header">
    <div class="container-nav">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Home
          <span class="glyphicon glyphicon-home"></span>
        </a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="#how-it-works">How it works<span class="sr-only">(current)</span></a></li>
          <li><a href=#schedule>Upcoming Schedule</a></li>
          <li><a href="/profiles">Wait List Rankings</a></li>
          <li><a href="/profiles/new">Your Profile </a></li>
          <li> <a href="/snippets" > Share an Idea</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li>  <a class="signed-in-nav" href=# ><%= current_user.email %></a> </li>
          <li> <%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
          <%else%>
          <li> <%= link_to 'Sign up', new_user_registration_path %></li>
          <li> <%= link_to 'Log in', new_user_session_path %></li>
          <%end%>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<div class="container-fluid">
    <div id="header-branding">
      <img class="header-image" src="../assets/citizen-debate-banner2.png" alt="logo banner TBD"/>
    <% if notice || alert %>
        <p id="notice"><%= notice %></p>
        <p class="alert-danger"><%= alert %></p>
    <%end%>
    <% if flash[:success] %>
    <div class="alert alert-success" role="alert">
      <%= flash[:success] %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    </div>
    <% end %>
    <% if flash[:info] %>
    <div class="alert alert-info" role="alert">
      <%= flash[:info] %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    </div>
    <% end %>
    <% if flash[:warning] %>
    <div class="alert alert-warning" role="alert">
      <%= flash[:warning] %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    </div>
    <% end %>
    <% if flash[:danger] %>
    <div class="alert alert-danger" role="alert">
      <%= flash[:danger] %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    </div>
    <% end %>
  </div>
  <%= yield %>
</div>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="#">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#about">About</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#services">Terms & Conditions</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#contact">Privacy Policy</a>
                        </li>
                    </ul6
                    <p class="copyright text-muted small">Copyright &copy; Rent Masters, LLC 2016. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

</body>
</html>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :display_name %><br>
    <%= f.text_field :display_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :political_affiliation %><br>
    <%= f.text_field :political_affiliation %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :about_me %><br>
    <%= f.text_field :about_me %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Back to profile', @profile %>

app/views/profiles/index.html.erb
<h1>Current Wait-list Order</h1>

<table>
  <thead>
    <tr>
      <th>Avatar </th>
      <th>Display name</th>
      <th>Profile ID </th>
      <th>User ID </th>
      <th>Rank </th>
      <th>Points </th>
      <th>City</th>
      <th>State</th>
      <th>Age</th>
      <th>Political affiliation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td> <%= image_tag profile.avatar.url(:thumb), alt:"avatar-img", class:"img-responsive img-thumbnail" %> </td>
        <td><%= profile.display_name %></td>
        <td><%= profile.id %></td>
        <td><%= profile.user_id %></td>
        <td><%= profile.user.rank %></td>
        <td><%= profile.user.points %></td>
        <td><%= profile.city %></td>
        <td><%= profile.state %></td>
        <td><%= profile.age %></td>
        <td><%= profile.political_affiliation %></td>
        <% if current_user && current_user.email == "bbensch@gmail.com" %>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user && current_user.email == "bbensch@gmail.com" %>
<%= link_to 'New Profile', new_profile_path %>
<% end %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<div>
  <%= image_tag @profile.avatar.url(:large), alt:"avatar-img", class:"img-responsive img-thumbnail" %>
</div>
<p>
  <strong>Your Display name:</strong>
  <%= @profile.display_name %>
</p>
<p>
  <strong>Wait List Ranking:</strong>
  <%= @profile.user.rank %>
</p>
<p>
  <strong>Accumulated Points:</strong>
  <%= @profile.user.points %>
</p>
<p>
  <strong>First name:</strong>
  <%= @profile.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @profile.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @profile.user.email %>
</p>
<p>
  <strong>City:</strong>
  <%= @profile.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @profile.state %>
</p>

<p>
  <strong>Age:</strong>
  <%= @profile.age %>
</p>

<p>
  <strong>About me:</strong>
  <%= @profile.about_me %>
</p>

<p>
  <strong>Political affiliation:</strong>
  <%= @profile.political_affiliation %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |

app/views/snippets/_form.html.erb
<%= form_for(@snippet) do |f| %>
  <% if @snippet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

      <ul>
      <% @snippet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h2> Why are you excited to use PRODUCT?:</h2>
    <%= f.text_area :body, size:"100x4" %>
  </div>
  <div class="field">
    <h2> How likely are you to recommend PRODUCT to a friend?</h2>
    <%= f.radio_button :rating, 1  %>
    <%= label_tag(:one, "1 - Unlikely", :class=> "nps") %>
    <%= f.radio_button :rating, 2  %>
    <%= label_tag(:two, "2", :class=> "nps") %>
    <%= f.radio_button :rating, 3  %>
    <%= label_tag(:three, "3", :class=> "nps") %>
    <%= f.radio_button :rating, 4  %>
    <%= label_tag(:two, "4", :class=> "nps") %>
    <%= f.radio_button :rating, 5  %>
    <%= label_tag(:three, "5", :class=> "nps") %>
    <%= f.radio_button :rating, 6  %>
    <%= label_tag(:two, "6", :class=> "nps") %>
    <%= f.radio_button :rating, 7  %>
    <%= label_tag(:three, "7", :class=> "nps") %>
    <%= f.radio_button :rating, 8  %>
    <%= label_tag(:two, "8", :class=> "nps") %>
    <%= f.radio_button :rating, 9  %>
    <%= label_tag(:three, "9", :class=> "nps") %>
    <%= f.radio_button :rating, 10 %>
    <%= label_tag(:ten, "10 - Most likely", :class=> "nps") %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/snippets/edit.html.erb
<h1>Editing Snippet</h1>

<%= render 'form' %>

<%= link_to 'Show', @snippet %> |
<%= link_to 'Back', snippets_path %>

app/views/snippets/index.html.erb
<h1>Your Previous Feedback</h1>

<table>
  <thead>
    <tr>
      <th>Why you want to use PRODUCT:</th>
      <th>Rating - How likely are you to recommend PRODUCT to a friend?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @snippets.each do |snippet| %>
      <tr>
        <td><%= snippet.body %></td>
        <td><%= snippet.rating %></td>
        <td><%= link_to 'Show', snippet %></td>
        <td><%= link_to 'Edit', edit_snippet_path(snippet) %></td>
        <% if current_user && current_user.email == "bbensch@gmail.com" %>
        <td><%= link_to 'Destroy', snippet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Share more feedback', new_snippet_path %>
<% if current_user && current_user.email == "bbensch@gmail.com" %>
<h3> <%= link_to 'View all feedback', '/admin_index' %> </h3>
<% end %>

app/views/snippets/new.html.erb
<h1>New Snippet</h1>

<%= render 'form' %>

<%= link_to 'Back', snippets_path %>

app/views/snippets/show.html.erb
<h1> Your Feedback </h1>
<p>
  <strong>Why you want to use PRODUCT:</strong>
  <br>
  <%= @snippet.body %>
</p>
<p>
  <strong>How likely are you to recommend PRODUCT to a friend?</strong>
  <br>
  <%= @snippet.rating %>
</p>

<%= link_to 'Edit', edit_snippet_path(@snippet) %> |
<%= link_to 'Back', snippets_path %>